### PR TITLE
Fix for text including brackets being included in at mention

### PR DESCRIPTION
**Pull request by Craby-Patty**
Current regex behaviour (https://regex101.com/r/gR79Ua/3),
Desired behaviour (https://regex101.com/r/gR79Ua/4)

### CODE REVIEW

**Review by wkeizer — APPROVED** [review]

**Comment by wkeizer** [comment]
Hi @jorritdenbroeder I've merged this change to develop. The regex to filter out the mention was changed a little bit. It couldn't cope with texts that had  brackets and a mention.

How can we get this to Master? Or is that an automated process?

Talk to you soon!

**Comment by jorritdenbroeder** [comment]
Hey @wkeizer & @Craby-Patty! Thanks for the fix, it looks like that regex was broken from the start :(

**Comment by jorritdenbroeder** [comment]
@wkeizer Packages have been published, so Github Actions is still doing it's job.

https://www.npmjs.com/search?q=atmention

**Comment by wkeizer** [comment]
Awesome, we will update our application with this new version. Cheers @jorritdenbroeder !

**Pull request merged**
